# Generated by Django 6.0.1 on 2026-03-11 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_add_board_and_sensor'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='board',
            table='board',
        ),
        migrations.AlterModelTable(
            name='sensor',
            table='sensor',
        ),
    ]
