# Generated by Django 6.0.1 on 2026-03-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0005_extend_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': ['board', 'sensor_model']},
        ),
        migrations.AddField(
            model_name='measurementtype',
            name='code',
            field=models.CharField(default='', max_length=32),
        ),
    ]
