# Generated by Django 6.0.1 on 2026-03-13 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0006_add_measurement_type_code'),
        ('sensor', '0006_alter_sensor_options'),
    ]

    operations = [
    ]
